version: '3'

# taskfile: curently only used on windows
# see: https://taskfile.dev/installation

env:
  PYTHON: python.exe


tasks:

  faust:
    cmds:
      - $PYTHON scripts/manage.py setup --faust
    status:
      - test -f lib/static/libfaust.lib

  sndfile:
    cmds:
      - $PYTHON scripts/manage.py setup --sndfile
    status:
      - test -f lib/status/libsndfile.lib

  samplerate:
    cmds:
      - $PYTHON scripts/manage.py setup --samplerate
    status:
      - test -f lib/status/libsamplerate.lib

  build:
    deps: [faust]
    cmds:
      - $PYTHON scripts/manage.py build
    sources:
      - src/cyfaust/*.pyx
      - src/cyfaust/*.pxd
      - src/cyfaust/*.cpp
    generates:
      - build/cyfaust/*.pyd

  build-static:
    deps: [faust]
    cmds:
      - $PYTHON scripts/manage.py build --static
    sources:
      - src/static/cyfaust/*.pyx
      - src/static/cyfaust/*.pxd
      - src/static/cyfaust/*.cpp
    generates:
      - build/static/cyfaust/*.pyd

  wheel:
    deps:
      - faust
      - clean
    cmds:
      - $PYTHON scripts/manage.py wheel --dynamic
    sources:
      - src/static/cyfaust/*.pyx
      - src/static/cyfaust/*.pxd
      - src/static/cyfaust/*.cpp
    generates:
      - wheels/*.whl

  wheel-static:
    deps:
      - faust
      - clean
    cmds:
      - $PYTHON scripts/manage.py wheel --static
    sources:
      - src/static/cyfaust/*.pyx
      - src/static/cyfaust/*.pxd
      - src/static/cyfaust/*.cpp
    generates:
      - wheels/*-static-*.whl

  release:
    deps:
      - faust
      - clean
    cmds:
      - $PYTHON scripts/manage.py wheel --release
      - task: test_wheel


  test_wheel:
    cmds:
      - $PYTHON scripts/manage.py wheel --test

  test:
    cmds:
      - $PYTHON scripts/manage.py test

  pytest:
    cmds:
      - $PYTHON scripts/manage.py test --pytest

  clean:
    silent: true
    cmds:
      - $PYTHON scripts/manage.py clean

  reset:
    silent: true
    cmds:
      - $PYTHON scripts/manage.py clean --reset

