version: '3'

# taskfile: curently only used on windows
# see: https://taskfile.dev/installation

env:
  PYTHON: python{{if eq OS "windows"}}.exe{{else}}3{{end}}


vars:
  LIBEXT: '{{if eq OS "windows"}}.lib{{else}}.a{{end}}'
  PYEXT: '{{if eq OS "windows"}}.pyd{{else}}.so{{end}}'


tasks:

  faust:
    cmds:
      - $PYTHON scripts/manage.py setup --faust
    status:
      - test -f lib/static/libfaust{{.LIBEXT}}

  sndfile:
    cmds:
      - $PYTHON scripts/manage.py setup --sndfile
    status:
      - test -f lib/status/libsndfile{{.LIBEXT}}

  samplerate:
    cmds:
      - $PYTHON scripts/manage.py setup --samplerate
    status:
      - test -f lib/status/libsamplerate{{.LIBEXT}}

  build:
    deps: [faust]
    cmds:
      - $PYTHON scripts/manage.py build
    sources:
      - src/cyfaust/*.pyx
      - src/cyfaust/*.pxd
      - src/cyfaust/*.cpp
    generates:
      - build/cyfaust/*{{.PYEXT}}

  build_static:
    deps: [faust]
    cmds:
      - $PYTHON scripts/manage.py build --static
    sources:
      - src/static/cyfaust/*.pyx
      - src/static/cyfaust/*.pxd
      - src/static/cyfaust/*.cpp
    generates:
      - build/static/cyfaust/*{{.PYEXT}}

  wheel:
    deps:
      - faust
      - clean
    cmds:
      - $PYTHON scripts/manage.py wheel --dynamic
    sources:
      - src/static/cyfaust/*.pyx
      - src/static/cyfaust/*.pxd
      - src/static/cyfaust/*.cpp
    generates:
      - wheels/*.whl

  wheel_static:
    deps:
      - faust
      - clean
    cmds:
      - $PYTHON scripts/manage.py wheel --static
    sources:
      - src/static/cyfaust/*.pyx
      - src/static/cyfaust/*.pxd
      - src/static/cyfaust/*.cpp
    generates:
      - wheels/*-static-*.whl

  release:
    deps:
      - faust
      - clean
    cmds:
      - $PYTHON scripts/manage.py wheel --release
      - task: test_wheel

  test:
    cmds:
      - $PYTHON scripts/manage.py test

  pytest:
    cmds:
      - $PYTHON scripts/manage.py test --pytest

  test_wheel:
    cmds:
      - $PYTHON scripts/manage.py wheel --test

  clean:
    cmds:
      - $PYTHON scripts/manage.py clean

  reset:
    cmds:
      - $PYTHON scripts/manage.py clean --reset

