
class CTree
typedef std::vector<CTree*> tvec

typedef CTree* Signal
typedef CTree* Box
typedef CTree* Tree

typedef Tree (*prim0)()
typedef Tree (*prim1)(Tree x)
typedef Tree (*prim2)(Tree x, Tree y)
typedef Tree (*prim3)(Tree x, Tree y, Tree z)
typedef Tree (*prim4)(Tree w, Tree x, Tree y, Tree z)
typedef Tree (*prim5)(Tree v, Tree w, Tree x, Tree y, Tree z)

const char* prim0name(prim0)
const char* prim1name(prim1)
const char* prim2name(prim2)
const char* prim3name(prim3)
const char* prim4name(prim4)
const char* prim5name(prim5)

const char* ffname(Signal s)
int ffarity(Signal s)

enum SType { kSInt, kSReal }
enum SOperator { kAdd, kSub, kMul, kDiv, kRem, kLsh, kARsh, kLRsh, kGT, kLT, kGE, kLE, kEQ, kNE, kAND, kOR, kXOR }

struct dsp_factory_base {
    virtual ~dsp_factory_base() {}
    virtual void write(std::ostream* , bool  = false, bool  = false) {}
}

string printBox(Box box, bool shared, int max_size)
string printSignal(Signal sig, bool shared, int max_size)
    
bool getDefNameProperty(Box b, Box& id)
string extractName(Box full_label)

void createLibContext()
void destroyLibContext()

bool isNil(Box b)
const char* tree2str(Box b)
int tree2int(Box b)
void* getUserData(Box b)

Box boxInt(int n)
Box boxReal(double n)   
Box boxWire()  
Box boxCut()
Box boxSeq(Box x, Box y)
Box boxPar(Box x, Box y)
Box boxPar3(Box x, Box y, Box z)
Box boxPar4(Box a, Box b, Box c, Box d)
Box boxPar5(Box a, Box b, Box c, Box d, Box e)
Box boxSplit(Box x, Box y)
Box boxMerge(Box x, Box y)
Box boxRec(Box x, Box y)
Box boxRoute(Box n, Box m, Box r)   
Box boxDelay()
Box boxDelay(Box b, Box del)   
Box boxIntCast()
Box boxIntCast(Box b)   
Box boxFloatCast()
Box boxFloatCast(Box b)   
Box boxReadOnlyTable()
Box boxReadOnlyTable(Box n, Box init, Box ridx)   
Box boxWriteReadTable()
Box boxWriteReadTable(Box n, Box init, Box widx, Box wsig, Box ridx)
Box boxWaveform(const tvec& wf)
Box boxSoundfile(const string& label, Box chan)
Box boxSoundfile(const string& label, Box chan, Box part, Box ridx)   
Box boxSelect2()
Box boxSelect2(Box selector, Box b1, Box b2)   
Box boxSelect3()
Box boxSelect3(Box selector, Box b1, Box b2, Box b3)
Box boxFConst(SType type, const string& name, const string& file)
Box boxFVar(SType type, const string& name, const string& file)
Box boxBinOp(SOperator op)
Box boxBinOp(SOperator op, Box b1, Box b2)   
Box boxAdd()
Box boxAdd(Box b1, Box b2)
Box boxSub()
Box boxSub(Box b1, Box b2)
Box boxMul()
Box boxMul(Box b1, Box b2)
Box boxDiv()
Box boxDiv(Box b1, Box b2)
Box boxRem()
Box boxRem(Box b1, Box b2)
Box boxLeftShift()
Box boxLeftShift(Box b1, Box b2)
Box boxLRightShift()
Box boxLRightShift(Box b1, Box b2)
Box boxARightShift()
Box boxARightShift(Box b1, Box b2)
Box boxGT()
Box boxGT(Box b1, Box b2)
Box boxLT()
Box boxLT(Box b1, Box b2)
Box boxGE()
Box boxGE(Box b1, Box b2)
Box boxLE()
Box boxLE(Box b1, Box b2)
Box boxEQ()
Box boxEQ(Box b1, Box b2)
Box boxNE()
Box boxNE(Box b1, Box b2)
Box boxAND()
Box boxAND(Box b1, Box b2)
Box boxOR()
Box boxOR(Box b1, Box b2)
Box boxXOR()
Box boxXOR(Box b1, Box b2)

Box boxAbs()
Box boxAbs(Box x)
Box boxAcos()
Box boxAcos(Box x)
Box boxTan()
Box boxTan(Box x)
Box boxSqrt()
Box boxSqrt(Box x)
Box boxSin()
Box boxSin(Box x)
Box boxRint()
Box boxRint(Box x)
Box boxRound()
Box boxRound(Box x)
Box boxLog()
Box boxLog(Box x)
Box boxLog10()
Box boxLog10(Box x)
Box boxFloor()
Box boxFloor(Box x)
Box boxExp()
Box boxExp(Box x)
Box boxExp10()
Box boxExp10(Box x)
Box boxCos()
Box boxCos(Box x)
Box boxCeil()
Box boxCeil(Box x)
Box boxAtan()
Box boxAtan(Box x)
Box boxAsin()
Box boxAsin(Box x)
Box boxRemainder()
Box boxRemainder(Box b1, Box b2)
Box boxPow()
Box boxPow(Box b1, Box b2)
Box boxMin()
Box boxMin(Box b1, Box b2)
Box boxMax()
Box boxMax(Box b1, Box b2)
Box boxFmod()
Box boxFmod(Box b1, Box b2)
Box boxAtan2()
Box boxAtan2(Box b1, Box b2)
Box boxButton(const string& label)
Box boxCheckbox(const string& label)
Box boxVSlider(const string& label, Box init, Box min, Box max, Box step)
Box boxHSlider(const string& label, Box init, Box min, Box max, Box step)
Box boxNumEntry(const string& label, Box init, Box min, Box max, Box step)
Box boxVBargraph(const string& label, Box min, Box max)
Box boxVBargraph(const string& label, Box min, Box max, Box x)
Box boxHBargraph(const string& label, Box min, Box max)
Box boxHBargraph(const string& label, Box min, Box max, Box x)
Box boxVGroup(const string& label, Box group)
Box boxHGroup(const string& label, Box group)
Box boxTGroup(const string& label, Box group)
Box boxAttach()
Box boxAttach(Box b1, Box b2)
Box boxPrim2(prim2 foo)   
bool isBoxAbstr(Box t)
bool isBoxAbstr(Box t, Box& x, Box& y)
bool isBoxAccess(Box t, Box& exp, Box& id)
bool isBoxAppl(Box t)
bool isBoxAppl(Box t, Box& x, Box& y)
bool isBoxButton(Box b)
bool isBoxButton(Box b, Box& lbl)
bool isBoxCase(Box b)
bool isBoxCase(Box b, Box& rules)
bool isBoxCheckbox(Box b)
bool isBoxCheckbox(Box b, Box& lbl)
bool isBoxComponent(Box b, Box& filename)
bool isBoxCut(Box t)
bool isBoxEnvironment(Box b)
bool isBoxError(Box t)
bool isBoxFConst(Box b)
bool isBoxFConst(Box b, Box& type, Box& name, Box& file)
bool isBoxFFun(Box b)
bool isBoxFFun(Box b, Box& ff)
bool isBoxFVar(Box b)
bool isBoxFVar(Box b, Box& type, Box& name, Box& file)
bool isBoxHBargraph(Box b)
bool isBoxHBargraph(Box b, Box& lbl, Box& min, Box& max)
bool isBoxHGroup(Box b)
bool isBoxHGroup(Box b, Box& lbl, Box& x)
bool isBoxHSlider(Box b)
bool isBoxHSlider(Box b, Box& lbl, Box& cur, Box& min, Box& max, Box& step)
bool isBoxIdent(Box t)
bool isBoxIdent(Box t, const char** str)
bool isBoxInputs(Box t, Box& x)
bool isBoxInt(Box t)
bool isBoxInt(Box t, int* i)
bool isBoxIPar(Box t, Box& x, Box& y, Box& z)
bool isBoxIProd(Box t, Box& x, Box& y, Box& z)
bool isBoxISeq(Box t, Box& x, Box& y, Box& z)
bool isBoxISum(Box t, Box& x, Box& y, Box& z)
bool isBoxLibrary(Box b, Box& filename)
bool isBoxMerge(Box t, Box& x, Box& y)
bool isBoxMetadata(Box b, Box& exp, Box& mdlist)
bool isBoxNumEntry(Box b)
bool isBoxNumEntry(Box b, Box& lbl, Box& cur, Box& min, Box& max, Box& step)
bool isBoxOutputs(Box t, Box& x)
bool isBoxPar(Box t, Box& x, Box& y)
bool isBoxPrim0(Box b)
bool isBoxPrim1(Box b)
bool isBoxPrim2(Box b)
bool isBoxPrim3(Box b)
bool isBoxPrim4(Box b)
bool isBoxPrim5(Box b)
bool isBoxPrim0(Box b, prim0* p)
bool isBoxPrim1(Box b, prim1* p)
bool isBoxPrim2(Box b, prim2* p)
bool isBoxPrim3(Box b, prim3* p)
bool isBoxPrim4(Box b, prim4* p)
bool isBoxPrim5(Box b, prim5* p)
bool isBoxReal(Box t)
bool isBoxReal(Box t, double* r)
bool isBoxRec(Box t, Box& x, Box& y)
bool isBoxRoute(Box b, Box& n, Box& m, Box& r)
bool isBoxSeq(Box t, Box& x, Box& y)
bool isBoxSlot(Box t)
bool isBoxSlot(Box t, int* id)
bool isBoxSoundfile(Box b)
bool isBoxSoundfile(Box b, Box& label, Box& chan)
bool isBoxSplit(Box t, Box& x, Box& y)
bool isBoxSymbolic(Box t)
bool isBoxSymbolic(Box t, Box& slot, Box& body)
bool isBoxTGroup(Box b)
bool isBoxTGroup(Box b, Box& lbl, Box& x)
bool isBoxVBargraph(Box b)
bool isBoxVBargraph(Box b, Box& lbl, Box& min, Box& max)
bool isBoxVGroup(Box b)
bool isBoxVGroup(Box b, Box& lbl, Box& x)
bool isBoxVSlider(Box b)
bool isBoxVSlider(Box b, Box& lbl, Box& cur, Box& min, Box& max, Box& step)
bool isBoxWaveform(Box b)
bool isBoxWire(Box t)
bool isBoxWithLocalDef(Box t, Box& body, Box& ldef)

Box DSPToBoxes(const string& name_app, const string& dsp_content, int argc, const char* argv[], int* inputs, int* outputs, string& error_msg)
bool getBoxType(Box box, int* inputs, int* outputs)
tvec boxesToSignals(Box box, string& error_msg)
string createSourceFromBoxes(const string& name_app, Box box, const string& lang, int argc, const char* argv[], string& error_msg)
