from enum import IntEnum
from typing import Iterator

from .signal import SignalVector

class SType(IntEnum):
    kSInt = 0
    kSReal = 1

class SOperator(IntEnum):
    kAdd = 0
    kSub = 1
    kMul = 2
    kDiv = 3
    kRem = 4
    kLsh = 5
    kARsh = 6
    kLRsh = 7
    kGT = 8
    kLT = 9
    kGE = 10
    kLE = 11
    kEQ = 12
    kNE = 13
    kAND = 14
    kOR = 15
    kXOR = 16

# -- Context manager --

class box_context:
    def __enter__(self) -> box_context: ...
    def __exit__(self, *args: object) -> None: ...

# -- BoxVector --

class BoxVector:
    def __init__(self) -> None: ...
    def __iter__(self) -> Iterator[Box]: ...
    def add(self, b: Box) -> None: ...
    def create_source(self, name_app: str, lang: str, *args: str) -> str: ...

# -- Box --

class Box:
    inputs: int
    outputs: int

    def __init__(self, value: int | float | None = None) -> None: ...
    @staticmethod
    def from_int(value: int) -> Box: ...
    @staticmethod
    def from_float(value: float) -> Box: ...
    @staticmethod
    def from_real(value: float) -> Box: ...
    @staticmethod
    def from_wire() -> Box: ...
    @staticmethod
    def from_cut() -> Box: ...
    @staticmethod
    def from_soundfile(
        label: str, chan: Box | int, part: Box | None, ridx: Box | int | None
    ) -> Box: ...
    @staticmethod
    def from_readonly_table(n: Box | int, init: Box, ridx: Box | int) -> Box: ...
    @staticmethod
    def from_write_read_table(
        n: Box | int, init: Box, widx: Box | int, wsig: Box, ridx: Box | int
    ) -> Box: ...
    @staticmethod
    def from_waveform(wf: BoxVector) -> Box: ...
    @staticmethod
    def from_fconst(type: SType, name: str, file: str) -> Box: ...
    @staticmethod
    def from_fvar(type: SType, name: str, file: str) -> Box: ...

    # Properties and representation
    def is_valid(self) -> bool: ...
    def to_string(self, shared: bool = False, max_size: int = 256) -> str: ...
    def print(self, shared: bool = False, max_size: int = 256) -> None: ...
    def create_source(self, name_app: str, lang: str, *args: str) -> str: ...
    def tree2str(self) -> str: ...
    def tree2int(self) -> int: ...
    def get_def_name_property(self) -> Box | None: ...
    def extract_name(self) -> str: ...

    # Operators
    def __add__(self, other: Box) -> Box: ...
    def __sub__(self, other: Box) -> Box: ...
    def __mul__(self, other: Box) -> Box: ...
    def __truediv__(self, other: Box) -> Box: ...
    def __mod__(self, other: Box) -> Box: ...
    def __eq__(self, other: object) -> Box: ...  # type: ignore[override]
    def __ne__(self, other: object) -> Box: ...  # type: ignore[override]
    def __gt__(self, other: Box) -> Box: ...
    def __ge__(self, other: Box) -> Box: ...
    def __lt__(self, other: Box) -> Box: ...
    def __le__(self, other: Box) -> Box: ...
    def __and__(self, other: Box) -> Box: ...
    def __or__(self, other: Box) -> Box: ...
    def __xor__(self, other: Box) -> Box: ...
    def __lshift__(self, other: Box) -> Box: ...
    def __rshift__(self, other: Box) -> Box: ...

    # Casting
    def int_cast(self) -> Box: ...
    def float_cast(self) -> Box: ...

    # Composition
    def seq(self, other: Box) -> Box: ...
    def par(self, other: Box) -> Box: ...
    def par3(self, b: Box, c: Box) -> Box: ...
    def par4(self, b: Box, c: Box, d: Box) -> Box: ...
    def par5(self, b: Box, c: Box, d: Box, e: Box) -> Box: ...
    def split(self, other: Box) -> Box: ...
    def merge(self, other: Box) -> Box: ...
    def rec(self, other: Box) -> Box: ...
    def delay(self, d: int | Box) -> Box: ...
    def select2(self, b1: Box, b2: Box) -> Box: ...
    def select3(self, b1: Box, b2: Box, b3: Box) -> Box: ...
    def arightshift(self, other: Box) -> Box: ...

    # Math (unary)
    def abs(self) -> Box: ...
    def acos(self) -> Box: ...
    def asin(self) -> Box: ...
    def atan(self) -> Box: ...
    def ceil(self) -> Box: ...
    def cos(self) -> Box: ...
    def exp(self) -> Box: ...
    def exp10(self) -> Box: ...
    def floor(self) -> Box: ...
    def log(self) -> Box: ...
    def log10(self) -> Box: ...
    def rint(self) -> Box: ...
    def round(self) -> Box: ...
    def sin(self) -> Box: ...
    def sqrt(self) -> Box: ...
    def tan(self) -> Box: ...

    # Type checking
    def is_nil(self) -> bool: ...
    def is_abstr(self) -> bool: ...
    def is_appl(self) -> bool: ...
    def is_button(self) -> bool: ...
    def is_case(self) -> bool: ...
    def is_checkbox(self) -> bool: ...
    def is_cut(self) -> bool: ...
    def is_environment(self) -> bool: ...
    def is_error(self) -> bool: ...
    def is_fconst(self) -> bool: ...
    def is_ffun(self) -> bool: ...
    def is_fvar(self) -> bool: ...
    def is_hbargraph(self) -> bool: ...
    def is_hgroup(self) -> bool: ...
    def is_hslider(self) -> bool: ...
    def is_ident(self) -> bool: ...
    def is_int(self) -> bool: ...
    def is_numentry(self) -> bool: ...
    def is_prim0(self) -> bool: ...
    def is_prim1(self) -> bool: ...
    def is_prim2(self) -> bool: ...
    def is_prim3(self) -> bool: ...
    def is_prim4(self) -> bool: ...
    def is_prim5(self) -> bool: ...
    def is_real(self) -> bool: ...
    def is_slot(self) -> bool: ...
    def is_soundfile(self) -> bool: ...
    def is_symbolic(self) -> bool: ...
    def is_tgroup(self) -> bool: ...
    def is_vbargraph(self) -> bool: ...
    def is_vgroup(self) -> bool: ...
    def is_vslider(self) -> bool: ...
    def is_waveform(self) -> bool: ...
    def is_wire(self) -> bool: ...

# -- Helper functions --

def box_or_int(var: Box | int) -> Box: ...
def box_or_float(var: Box | float) -> Box: ...
def box_or_number(var: Box | float | int) -> Box: ...

# -- Context / factory --

def create_lib_context() -> None: ...
def destroy_lib_context() -> None: ...
def dsp_to_boxes(name_app: str, dsp_content: str, *args: str) -> Box | None: ...
def get_box_type(b: Box) -> tuple[int, int] | None: ...
def boxes_to_signals(b: Box) -> SignalVector | None: ...
def create_source_from_boxes(name_app: str, box: Box, lang: str, *args: str) -> str | None: ...

# -- Utility --

def to_string(box: Box, shared: bool, max_size: int) -> str: ...
def print_box(box: Box, shared: bool, max_size: int) -> str: ...
def get_def_name_property(b: Box) -> Box | None: ...
def extract_name(full_label: Box) -> str: ...
def box_is_nil(b: Box) -> bool: ...
def tree2str(b: Box) -> str: ...
def tree2int(b: Box) -> int: ...

# -- Primitive boxes --

def box_int(n: int) -> Box: ...
def box_float(n: float) -> Box: ...
def box_real(n: float) -> Box: ...
def box_wire() -> Box: ...
def box_cut() -> Box: ...

# -- Composition --

def box_seq(x: Box, y: Box) -> Box: ...
def box_par(x: Box, y: Box) -> Box: ...
def box_par3(x: Box, y: Box, z: Box) -> Box: ...
def box_par4(a: Box, b: Box, c: Box, d: Box) -> Box: ...
def box_par5(a: Box, b: Box, c: Box, d: Box, e: Box) -> Box: ...
def box_split(x: Box, y: Box) -> Box: ...
def box_merge(x: Box, y: Box) -> Box: ...
def box_rec(x: Box, y: Box) -> Box: ...
def box_route(n: Box, m: Box, r: Box) -> Box: ...

# -- Delay / cast / table --

def box_delay_op() -> Box: ...
def box_delay(b: Box, d: Box) -> Box: ...
def box_int_cast_op() -> Box: ...
def box_int_cast(b: Box) -> Box: ...
def box_float_cast_op() -> Box: ...
def box_float_cast(b: Box) -> Box: ...
def box_readonly_table_op() -> Box: ...
def box_readonly_table(n: Box, init: Box, ridx: Box) -> Box: ...
def box_write_read_table_op() -> Box: ...
def box_write_read_table(n: Box, init: Box, widx: Box, wsig: Box, ridx: Box) -> Box: ...
def box_waveform(wf: BoxVector) -> Box: ...
def box_soundfile(label: str, chan: Box | int, part: Box | None, ridx: Box | int | None) -> Box: ...
def box_select2(selector: Box, b1: Box, b2: Box) -> Box: ...
def box_select2_op() -> Box: ...
def box_select3(selector: Box, b1: Box, b2: Box, b3: Box) -> Box: ...
def box_fconst(type: SType, name: str, file: str) -> Box: ...
def box_fvar(type: SType, name: str, file: str) -> Box: ...
def box_bin_op0(op: SOperator) -> Box: ...
def box_bin_op(op: SOperator, b1: Box, b2: Box) -> Box: ...

# -- Arithmetic --

def box_add_op() -> Box: ...
def box_add(b1: Box, b2: Box) -> Box: ...
def box_sub_op() -> Box: ...
def box_sub(b1: Box, b2: Box) -> Box: ...
def box_mul_op() -> Box: ...
def box_mul(b1: Box, b2: Box) -> Box: ...
def box_div_op() -> Box: ...
def box_div(b1: Box, b2: Box) -> Box: ...
def box_rem_op() -> Box: ...
def box_rem(b1: Box, b2: Box) -> Box: ...

# -- Bitwise --

def box_leftshift_op() -> Box: ...
def box_leftshift(b1: Box, b2: Box) -> Box: ...
def box_lrightshift_op() -> Box: ...
def box_lrightshift(b1: Box, b2: Box) -> Box: ...
def box_arightshift_op() -> Box: ...
def box_arightshift(b1: Box, b2: Box) -> Box: ...

# -- Comparison --

def box_gt_op() -> Box: ...
def box_gt(b1: Box, b2: Box) -> Box: ...
def box_lt_op() -> Box: ...
def box_lt(b1: Box, b2: Box) -> Box: ...
def box_ge_op() -> Box: ...
def box_ge(b1: Box, b2: Box) -> Box: ...
def box_le_op() -> Box: ...
def box_le(b1: Box, b2: Box) -> Box: ...
def box_eq_op() -> Box: ...
def box_eq(b1: Box, b2: Box) -> Box: ...
def box_ne_op() -> Box: ...
def box_ne(b1: Box, b2: Box) -> Box: ...

# -- Logical --

def box_and_op() -> Box: ...
def box_and(b1: Box, b2: Box) -> Box: ...
def box_or_op() -> Box: ...
def box_or(b1: Box, b2: Box) -> Box: ...
def box_xor_op() -> Box: ...
def box_xor(b1: Box, b2: Box) -> Box: ...

# -- Math (unary) --

def box_abs_op() -> Box: ...
def box_abs(x: Box) -> Box: ...
def box_acos_op() -> Box: ...
def box_acos(x: Box) -> Box: ...
def box_asin_op() -> Box: ...
def box_asin(x: Box) -> Box: ...
def box_atan_op() -> Box: ...
def box_atan(x: Box) -> Box: ...
def box_ceil_op() -> Box: ...
def box_ceil(x: Box) -> Box: ...
def box_cos_op() -> Box: ...
def box_cos(x: Box) -> Box: ...
def box_exp_op() -> Box: ...
def box_exp(x: Box) -> Box: ...
def box_exp10_op() -> Box: ...
def box_exp10(x: Box) -> Box: ...
def box_floor_op() -> Box: ...
def box_floor(x: Box) -> Box: ...
def box_log_op() -> Box: ...
def box_log(x: Box) -> Box: ...
def box_log10_op() -> Box: ...
def box_log10(x: Box) -> Box: ...
def box_rint_op() -> Box: ...
def box_rint(x: Box) -> Box: ...
def box_round_op() -> Box: ...
def box_round(x: Box) -> Box: ...
def box_sin_op() -> Box: ...
def box_sin(x: Box) -> Box: ...
def box_sqrt_op() -> Box: ...
def box_sqrt(x: Box) -> Box: ...
def box_tan_op() -> Box: ...
def box_tan(x: Box) -> Box: ...

# -- Math (binary) --

def box_remainder_op() -> Box: ...
def box_remainder(b1: Box, b2: Box) -> Box: ...
def box_pow_op() -> Box: ...
def box_pow(b1: Box, b2: Box) -> Box: ...
def box_min_op() -> Box: ...
def box_min(b1: Box, b2: Box) -> Box: ...
def box_max_op() -> Box: ...
def box_max(b1: Box, b2: Box) -> Box: ...
def box_fmod_op() -> Box: ...
def box_fmod(b1: Box, b2: Box) -> Box: ...
def box_atan2_op() -> Box: ...
def box_atan2(b1: Box, b2: Box) -> Box: ...

# -- UI controls --

def box_button(label: str) -> Box: ...
def box_checkbox(label: str) -> Box: ...
def box_vslider(label: str, init: Box, min: Box, max: Box, step: Box) -> Box: ...
def box_hslider(label: str, init: Box, min: Box, max: Box, step: Box) -> Box: ...
def box_numentry(label: str, init: Box, min: Box, max: Box, step: Box) -> Box: ...
def box_vbargraph(label: str, min: Box, max: Box) -> Box: ...
def box_vbargraph2(label: str, min: Box, max: Box, x: Box) -> Box: ...
def box_hbargraph(label: str, min: Box, max: Box) -> Box: ...
def box_hbargraph2(label: str, min: Box, max: Box, x: Box) -> Box: ...
def box_vgroup(label: str, group: Box) -> Box: ...
def box_hgroup(label: str, group: Box) -> Box: ...
def box_tgroup(label: str, group: Box) -> Box: ...
def box_attach_op() -> Box: ...
def box_attach(b1: Box, b2: Box) -> Box: ...

# -- Type checking --

def is_box_abstr(t: Box) -> bool: ...
def is_box_appl(t: Box) -> bool: ...
def is_box_button(b: Box) -> bool: ...
def is_box_case(b: Box) -> bool: ...
def is_box_checkbox(b: Box) -> bool: ...
def is_box_cut(t: Box) -> bool: ...
def is_box_environment(b: Box) -> bool: ...
def is_box_error(t: Box) -> bool: ...
def is_box_fconst(b: Box) -> bool: ...
def is_box_ffun(b: Box) -> bool: ...
def is_box_fvar(b: Box) -> bool: ...
def is_box_hbargraph(b: Box) -> bool: ...
def is_box_hgroup(b: Box) -> bool: ...
def is_box_hslider(b: Box) -> bool: ...
def is_box_ident(t: Box) -> bool: ...
def is_box_int(t: Box) -> bool: ...
def get_box_id(t: Box) -> str | None: ...
def getparams_box_abstr(t: Box) -> dict[str, object]: ...
def getparams_box_access(t: Box) -> dict[str, object]: ...
def getparams_box_appl(t: Box) -> dict[str, object]: ...
def getparams_box_button(b: Box) -> dict[str, object]: ...
def getparams_box_case(b: Box) -> dict[str, object]: ...
def getparams_box_checkbox(b: Box) -> dict[str, object]: ...
def getparams_box_component(b: Box) -> dict[str, object]: ...
def getparams_box_fconst(b: Box) -> dict[str, object]: ...
def getparams_box_ffun(b: Box) -> dict[str, object]: ...
def getparams_box_fvar(b: Box) -> dict[str, object]: ...
def getparams_box_hbargraph(b: Box) -> dict[str, object]: ...
def getparams_box_hgroup(b: Box) -> dict[str, object]: ...
def getparams_box_hslider(b: Box) -> dict[str, object]: ...
def getparams_box_inputs(t: Box) -> dict[str, object]: ...
