from typing import Any

from .box import Box
from .signal import SignalVector

def get_version() -> str: ...
def generate_sha1(data: str) -> str: ...
def expand_dsp_from_file(filename: str, *args: str) -> tuple[str, str] | None: ...
def expand_dsp_from_string(
    name_app: str, dsp_content: str, *args: str
) -> tuple[str, str] | None: ...
def generate_auxfiles_from_file(filename: str, *args: str) -> bool: ...
def generate_auxfiles_from_string(name_app: str, dsp_content: str, *args: str) -> bool: ...
def get_dsp_factory_from_sha_key(sha_key: str) -> InterpreterDspFactory: ...
def create_dsp_factory_from_file(filename: str, *args: str) -> InterpreterDspFactory | None: ...
def create_dsp_factory_from_string(
    name_app: str, code: str, *args: str
) -> InterpreterDspFactory | None: ...
def create_dsp_factory_from_signals(
    name_app: str, signals: SignalVector, *args: str
) -> InterpreterDspFactory | None: ...
def create_dsp_factory_from_boxes(
    name_app: str, box: Box, *args: str
) -> InterpreterDspFactory | None: ...
def delete_all_dsp_factories() -> None: ...
def get_all_dsp_factories() -> list[str]: ...
def start_multithreaded_access_mode() -> bool: ...
def stop_multithreaded_access_mode() -> None: ...
def read_dsp_factory_from_bitcode(
    bitcode: str,
) -> InterpreterDspFactory | None: ...
def read_dsp_factory_from_bitcode_file(
    bitcode_path: str,
) -> InterpreterDspFactory | None: ...

class RtAudioDriver:
    def __init__(self, srate: int, bsize: int) -> None: ...
    def set_dsp(self, dsp: InterpreterDsp) -> None: ...
    def init(self, dsp: InterpreterDsp) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def buffersize(self) -> int: ...
    @property
    def samplerate(self) -> int: ...
    @property
    def numinputs(self) -> int: ...
    @property
    def numoutputs(self) -> int: ...

class InterpreterDspFactory:
    def get_name(self) -> str: ...
    def get_sha_key(self) -> str: ...
    def get_dsp_code(self) -> str: ...
    def get_compile_options(self) -> str: ...
    def get_library_list(self) -> list[str]: ...
    def get_include_pathnames(self) -> list[str]: ...
    def get_warning_messages(self) -> list[str]: ...
    def create_dsp_instance(self) -> InterpreterDsp: ...
    def set_memory_manager(self, manager: Any) -> None: ...
    def get_memory_manager(self) -> Any: ...
    def class_init(self, sample_rate: int) -> None: ...
    def write_to_bitcode(self) -> str: ...
    def write_to_bitcode_file(self, bit_code_path: str) -> bool: ...
    @staticmethod
    def from_sha_key(sha_key: str) -> InterpreterDspFactory: ...
    @staticmethod
    def from_file(filepath: str, *args: str) -> InterpreterDspFactory | None: ...
    @staticmethod
    def from_string(name_app: str, code: str, *args: str) -> InterpreterDspFactory | None: ...
    @staticmethod
    def from_signals(
        name_app: str, signals: SignalVector, *args: str
    ) -> InterpreterDspFactory | None: ...
    @staticmethod
    def from_boxes(name_app: str, box: Box, *args: str) -> InterpreterDspFactory | None: ...
    @staticmethod
    def from_bitcode_file(
        bit_code_path: str,
    ) -> InterpreterDspFactory | None: ...
    @staticmethod
    def from_bitcode(bitcode: str) -> InterpreterDspFactory | None: ...

class MetaCollector:
    def get_metadata(self) -> dict[str, str]: ...

class InterpreterDsp:
    def delete(self) -> None: ...
    def get_numinputs(self) -> int: ...
    def get_numoutputs(self) -> int: ...
    def get_samplerate(self) -> int: ...
    def init(self, sample_rate: int) -> None: ...
    def instance_init(self, sample_rate: int) -> None: ...
    def instance_constants(self, sample_rate: int) -> None: ...
    def instance_reset_user_interface(self) -> None: ...
    def instance_clear(self) -> None: ...
    def clone(self) -> InterpreterDsp: ...
    def build_user_interface(self, sound_directory: str = "", sample_rate: int = -1) -> None: ...
    def control(self) -> None: ...
    def frame(self, inputs: Any, outputs: Any) -> None: ...
    def compute(self, count: int, inputs: Any, outputs: Any) -> None: ...
    def compute_timestamped(
        self, date_usec: float, count: int, inputs: Any, outputs: Any
    ) -> None: ...
    def metadata(self) -> dict[str, str]: ...
