from typing import Any

class SoundBasePlayer:
    def __init__(self, filename: str) -> None: ...
    def get_num_inputs(self) -> int: ...
    def get_num_outputs(self) -> int: ...
    def get_sample_rate(self) -> int: ...
    def init(self, sample_rate: int) -> None: ...
    def instance_init(self, sample_rate: int) -> None: ...
    def instance_constants(self, sample_rate: int) -> None: ...
    def instance_reset_user_interface(self) -> None: ...
    def instance_clear(self) -> None: ...
    @property
    def filename(self) -> str: ...
    def compute(self, count: int, inputs: Any, outputs: Any) -> None: ...

class SoundMemoryPlayer(SoundBasePlayer):
    def __init__(self, filename: str) -> None: ...

class SoundDtdPlayer(SoundBasePlayer):
    def __init__(self, filename: str) -> None: ...

class SoundPositionManager:
    def __init__(self) -> None: ...
    def add_dsp(self, player: SoundBasePlayer) -> None: ...
    def remove_dsp(self, player: SoundBasePlayer) -> None: ...

def create_memory_player(filename: str) -> SoundMemoryPlayer: ...
def create_dtd_player(filename: str) -> SoundDtdPlayer: ...
def create_position_manager() -> SoundPositionManager: ...
