from enum import IntEnum
from typing import Any, Iterator

class SType(IntEnum):
    kSInt = 0
    kSReal = 1

class SOperator(IntEnum):
    kAdd = 0
    kSub = 1
    kMul = 2
    kDiv = 3
    kRem = 4
    kLsh = 5
    kARsh = 6
    kLRsh = 7
    kGT = 8
    kLT = 9
    kGE = 10
    kLE = 11
    kEQ = 12
    kNE = 13
    kAND = 14
    kOR = 15
    kXOR = 16

# -- Context manager --

class signal_context:
    def __enter__(self) -> signal_context: ...
    def __exit__(self, *args: object) -> None: ...

# -- Interval --

class Interval:
    def __init__(self, lo: float, hi: float, lsb: int) -> None: ...
    @property
    def low(self) -> float: ...
    @property
    def high(self) -> float: ...
    @property
    def lsb(self) -> float: ...

# -- SignalVector --

class SignalVector:
    def __init__(self) -> None: ...
    def __iter__(self) -> Iterator[Signal]: ...
    def add(self, sig: Signal) -> None: ...
    def create_source(self, name_app: str, lang: str, *args: str) -> str: ...
    def simplify_to_normal_form(self) -> SignalVector: ...

# -- Signal --

class Signal:
    def __init__(self) -> None: ...
    @staticmethod
    def from_input(idx: int) -> Signal: ...
    @staticmethod
    def from_int(value: int) -> Signal: ...
    @staticmethod
    def from_float(value: float) -> Signal: ...
    @staticmethod
    def from_real(value: float) -> Signal: ...
    @staticmethod
    def from_soundfile(label: str) -> Signal: ...
    @staticmethod
    def from_button(label: str) -> Signal: ...
    @staticmethod
    def from_checkbox(label: str) -> Signal: ...
    @staticmethod
    def from_vslider(
        label: str,
        init: float | Signal,
        min: float | Signal,
        max: float | Signal,
        step: float | Signal,
    ) -> Signal: ...
    @staticmethod
    def from_hslider(
        label: str,
        init: float | Signal,
        min: float | Signal,
        max: float | Signal,
        step: float | Signal,
    ) -> Signal: ...
    @staticmethod
    def from_numentry(
        label: str,
        init: float | Signal,
        min: float | Signal,
        max: float | Signal,
        step: float | Signal,
    ) -> Signal: ...
    @staticmethod
    def from_read_only_table(n: int | Signal, init: Signal, ridx: int | Signal) -> Signal: ...
    @staticmethod
    def from_write_read_table(
        n: int, init: Signal, widx: int, wsig: Signal, ridx: int
    ) -> Signal: ...

    # Representation
    def create_source(self, name_app: str, lang: str, *args: str) -> str: ...
    def simplify_to_normal_form(self) -> Signal: ...
    def to_string(self, shared: bool = False, max_size: int = 256) -> str: ...
    def print(self, shared: bool = False, max_size: int = 256) -> None: ...
    def ffname(self) -> str: ...
    def ffarity(self) -> int: ...

    # Operators
    def __add__(self, other: Signal | float | int) -> Signal: ...
    def __radd__(self, other: float | int) -> Signal: ...
    def __sub__(self, other: Signal | float | int) -> Signal: ...
    def __rsub__(self, other: float | int) -> Signal: ...
    def __mul__(self, other: Signal | float | int) -> Signal: ...
    def __rmul__(self, other: float | int) -> Signal: ...
    def __truediv__(self, other: Signal | float | int) -> Signal: ...
    def __rtruediv__(self, other: float | int) -> Signal: ...
    def __mod__(self, other: Signal) -> Signal: ...
    def __eq__(self, other: object) -> Signal: ...  # type: ignore[override]
    def __ne__(self, other: object) -> Signal: ...  # type: ignore[override]
    def __gt__(self, other: Signal) -> Signal: ...
    def __ge__(self, other: Signal) -> Signal: ...
    def __lt__(self, other: Signal) -> Signal: ...
    def __le__(self, other: Signal) -> Signal: ...
    def __and__(self, other: Signal) -> Signal: ...
    def __or__(self, other: Signal) -> Signal: ...
    def __xor__(self, other: Signal) -> Signal: ...
    def __lshift__(self, other: Signal) -> Signal: ...
    def __rshift__(self, other: Signal) -> Signal: ...

    # Casting
    def int_cast(self) -> Signal: ...
    def float_cast(self) -> Signal: ...

    # Composition
    def attach(self, other: Signal) -> Signal: ...
    def delay(self, d: Signal) -> Signal: ...
    def select2(self, s1: Signal, s2: Signal) -> Signal: ...
    def select3(self, s1: Signal, s2: Signal, s3: Signal) -> Signal: ...
    def recursion(self) -> Signal: ...
    def self_rec(self) -> Signal: ...
    def self_n(self, id: int) -> Signal: ...
    def recursion_n(self, rf: SignalVector) -> SignalVector: ...
    def vbargraph(self, label: str, min: float | Signal, max: float | Signal) -> Signal: ...
    def hbargraph(self, label: str, min: float | Signal, max: float | Signal) -> Signal: ...

    # Math (unary)
    def abs(self) -> Signal: ...
    def acos(self) -> Signal: ...
    def asin(self) -> Signal: ...
    def atan(self) -> Signal: ...
    def ceil(self) -> Signal: ...
    def cos(self) -> Signal: ...
    def exp(self) -> Signal: ...
    def exp10(self) -> Signal: ...
    def floor(self) -> Signal: ...
    def log(self) -> Signal: ...
    def log10(self) -> Signal: ...
    def rint(self) -> Signal: ...
    def sin(self) -> Signal: ...
    def sqrt(self) -> Signal: ...
    def tan(self) -> Signal: ...

    # Math (binary)
    def remainder(self, other: Signal) -> Signal: ...
    def pow(self, other: Signal) -> Signal: ...
    def min(self, other: Signal) -> Signal: ...
    def max(self, other: Signal) -> Signal: ...
    def fmod(self, other: Signal) -> Signal: ...

    # Type checking
    def is_int(self) -> dict[str, Any]: ...
    def is_float(self) -> dict[str, Any]: ...
    def is_input(self) -> dict[str, Any]: ...
    def is_output(self) -> dict[str, Any]: ...
    def is_delay1(self) -> dict[str, Any]: ...
    def is_delay(self) -> dict[str, Any]: ...
    def is_prefix(self) -> dict[str, Any]: ...
    def is_read_table(self) -> dict[str, Any]: ...
    def is_write_table(self) -> dict[str, Any]: ...
    def is_gen(self) -> dict[str, Any]: ...
    def is_doc_constant_tbl(self) -> dict[str, Any]: ...
    def is_doc_write_tbl(self) -> dict[str, Any]: ...
    def is_doc_access_tbl(self) -> dict[str, Any]: ...
    def is_select2(self) -> dict[str, Any]: ...
    def is_assert_bounds(self) -> dict[str, Any]: ...
    def is_highest(self) -> dict[str, Any]: ...
    def is_lowest(self) -> dict[str, Any]: ...
    def is_bin_op(self) -> dict[str, Any]: ...
    def is_ffun(self) -> dict[str, Any]: ...
    def is_fconst(self) -> dict[str, Any]: ...
    def is_fvar(self) -> dict[str, Any]: ...
    def is_proj(self) -> dict[str, Any]: ...
    def is_rec(self) -> dict[str, Any]: ...
    def is_int_cast(self) -> dict[str, Any]: ...
    def is_float_cast(self) -> dict[str, Any]: ...
    def is_button(self) -> dict[str, Any]: ...
    def is_checkbox(self) -> dict[str, Any]: ...
    def is_waveform(self) -> bool: ...
    def is_hslider(self) -> dict[str, Any]: ...
    def is_vslider(self) -> dict[str, Any]: ...
    def is_num_entry(self) -> dict[str, Any]: ...
    def is_hbargraph(self) -> dict[str, Any]: ...
    def is_vbargraph(self) -> dict[str, Any]: ...
    def is_attach(self) -> dict[str, Any]: ...
    def is_enable(self) -> dict[str, Any]: ...
    def is_control(self) -> dict[str, Any]: ...
    def is_soundfile(self) -> dict[str, Any]: ...
    def is_soundfile_length(self) -> dict[str, Any]: ...
    def is_soundfile_rate(self) -> dict[str, Any]: ...
    def is_soundfile_buffer(self) -> dict[str, Any]: ...

# -- Helper functions --

def sig_or_float(var: Signal | float) -> Signal: ...
def sig_or_int(var: Signal | int) -> Signal: ...

# -- Context / factory --

def create_lib_context() -> None: ...
def destroy_lib_context() -> None: ...

# -- Utility --

def ffname(s: Signal) -> str: ...
def ffarity(s: Signal) -> int: ...
def print_signal(sig: Signal, shared: bool, max_size: int) -> str: ...
def is_nil(s: Signal) -> bool: ...
def tree2str(s: Signal) -> str: ...
def xtended_arity(s: Signal) -> int: ...
def xtended_name(s: Signal) -> str: ...

# -- Signal creation --

def sig_int(n: int) -> Signal: ...
def sig_real(n: float) -> Signal: ...
def sig_float(n: float) -> Signal: ...
def sig_input(idx: int) -> Signal: ...
def sig_delay(s: Signal, d: Signal) -> Signal: ...
def sig_delay1(s: Signal) -> Signal: ...
def sig_int_cast(s: Signal) -> Signal: ...
def sig_float_cast(s: Signal) -> Signal: ...
def sig_readonly_table(n: Signal, init: Signal, ridx: Signal) -> Signal: ...
def sig_write_read_table(
    n: Signal, init: Signal, widx: Signal, wsig: Signal, ridx: Signal
) -> Signal: ...
def sig_waveform_int(view: Any) -> Signal: ...
def sig_waveform_float(view: Any) -> Signal: ...
def sig_soundfile(*paths: str) -> Signal: ...
def sig_soundfile_length(sf: Signal, part: Signal) -> Signal: ...
def sig_soundfile_rate(sf: Signal, part: Signal) -> Signal: ...
def sig_soundfile_buffer(sf: Signal, chan: Signal, part: Signal, ridx: Signal) -> Signal: ...
def sig_select2(selector: Signal, s1: Signal, s2: Signal) -> Signal: ...
def sig_select3(selector: Signal, s1: Signal, s2: Signal, s3: Signal) -> Signal: ...
def sig_fconst(type: SType, name: str, file: str) -> Signal: ...
def sig_fvar(type: SType, name: str, file: str) -> Signal: ...

# -- Binary operations --

def sig_bin_op(op: SOperator, x: Signal, y: Signal) -> Signal: ...
def sig_add(x: Signal, y: Signal) -> Signal: ...
def sig_sub(x: Signal, y: Signal) -> Signal: ...
def sig_mul(x: Signal, y: Signal) -> Signal: ...
def sig_div(x: Signal, y: Signal) -> Signal: ...
def sig_rem(x: Signal, y: Signal) -> Signal: ...
def sig_leftshift(x: Signal, y: Signal) -> Signal: ...
def sig_lrightshift(x: Signal, y: Signal) -> Signal: ...
def sig_arightshift(x: Signal, y: Signal) -> Signal: ...
def sig_gt(x: Signal, y: Signal) -> Signal: ...
def sig_lt(x: Signal, y: Signal) -> Signal: ...
def sig_ge(x: Signal, y: Signal) -> Signal: ...
def sig_le(x: Signal, y: Signal) -> Signal: ...
def sig_eq(x: Signal, y: Signal) -> Signal: ...
def sig_ne(x: Signal, y: Signal) -> Signal: ...
def sig_and(x: Signal, y: Signal) -> Signal: ...
def sig_or(x: Signal, y: Signal) -> Signal: ...
def sig_xor(x: Signal, y: Signal) -> Signal: ...

# -- Math (unary) --

def sig_abs(x: Signal) -> Signal: ...
def sig_acos(x: Signal) -> Signal: ...
def sig_asin(x: Signal) -> Signal: ...
def sig_atan(x: Signal) -> Signal: ...
def sig_ceil(x: Signal) -> Signal: ...
def sig_cos(x: Signal) -> Signal: ...
def sig_exp(x: Signal) -> Signal: ...
def sig_exp10(x: Signal) -> Signal: ...
def sig_floor(x: Signal) -> Signal: ...
def sig_log(x: Signal) -> Signal: ...
def sig_log10(x: Signal) -> Signal: ...
def sig_rint(x: Signal) -> Signal: ...
def sig_sin(x: Signal) -> Signal: ...
def sig_sqrt(x: Signal) -> Signal: ...
def sig_tan(x: Signal) -> Signal: ...

# -- Math (binary) --

def sig_remainder(x: Signal, y: Signal) -> Signal: ...
def sig_pow(x: Signal, y: Signal) -> Signal: ...
def sig_min(x: Signal, y: Signal) -> Signal: ...
def sig_max(x: Signal, y: Signal) -> Signal: ...
def sig_fmod(x: Signal, y: Signal) -> Signal: ...
def sig_atan2(x: Signal, y: Signal) -> Signal: ...

# -- Recursion --

def sig_self() -> Signal: ...
def sig_recursion(s: Signal) -> Signal: ...
def sig_self_n(id: int) -> Signal: ...
def sig_recursion_n(rf: SignalVector) -> SignalVector: ...

# -- UI controls --

def sig_button(label: str) -> Signal: ...
def sig_checkbox(label: str) -> Signal: ...
def sig_vslider(label: str, init: Signal, min: Signal, max: Signal, step: Signal) -> Signal: ...
def sig_hslider(label: str, init: Signal, min: Signal, max: Signal, step: Signal) -> Signal: ...
def sig_numentry(label: str, init: Signal, min: Signal, max: Signal, step: Signal) -> Signal: ...
def sig_vbargraph(label: str, min: Signal, max: Signal, s: Signal) -> Signal: ...
def sig_hbargraph(label: str, min: Signal, max: Signal, s: Signal) -> Signal: ...
def sig_attach(s1: Signal, s2: Signal) -> Signal: ...

# -- Normalization --

def simplify_to_normal_form(s: Signal) -> Signal: ...
def simplify_to_normal_form2(vec: SignalVector) -> SignalVector: ...

# -- Source generation --

def create_source_from_signals(
    name_app: str, osigs: SignalVector, lang: str, *args: str
) -> str | None: ...

# -- Type checking (module-level) --

def is_sig_int(t: Signal) -> dict[str, Any]: ...
def is_sig_float(t: Signal) -> dict[str, Any]: ...
def is_sig_real(t: Signal) -> dict[str, Any]: ...
def is_sig_input(t: Signal) -> dict[str, Any]: ...
def is_sig_output(t: Signal) -> dict[str, Any]: ...
def is_sig_delay1(t: Signal) -> dict[str, Any]: ...
def is_sig_delay(t: Signal) -> dict[str, Any]: ...
def is_sig_prefix(t: Signal) -> dict[str, Any]: ...
def is_sig_readonly_table(s: Signal) -> dict[str, Any]: ...
def is_sig_read_write_table(u: Signal) -> dict[str, Any]: ...
def is_sig_gen(t: Signal) -> dict[str, Any]: ...
def is_sig_doc_constant_tbl(t: Signal) -> dict[str, Any]: ...
def is_sig_doc_write_tbl(t: Signal) -> dict[str, Any]: ...
def is_sig_doc_access_tbl(t: Signal) -> dict[str, Any]: ...
def is_sig_select2(t: Signal) -> dict[str, Any]: ...
def is_sig_assert_bounds(t: Signal) -> dict[str, Any]: ...
def is_sig_highest(t: Signal) -> dict[str, Any]: ...
def is_sig_lowest(t: Signal) -> dict[str, Any]: ...
def is_sig_bin_op(s: Signal) -> dict[str, Any]: ...
def is_sig_ffun(s: Signal) -> dict[str, Any]: ...
def is_sig_fconst(s: Signal) -> dict[str, Any]: ...
def is_sig_fvar(s: Signal) -> dict[str, Any]: ...
def is_proj(s: Signal) -> dict[str, Any]: ...
def is_rec(s: Signal) -> dict[str, Any]: ...
def is_sig_int_cast(s: Signal) -> dict[str, Any]: ...
def is_sig_float_cast(s: Signal) -> dict[str, Any]: ...
def is_sig_button(s: Signal) -> dict[str, Any]: ...
def is_sig_checkbox(s: Signal) -> dict[str, Any]: ...
def is_sig_waveform(s: Signal) -> bool: ...
def is_sig_hslider(u: Signal) -> dict[str, Any]: ...
def is_sig_vslider(u: Signal) -> dict[str, Any]: ...
def is_sig_numentry(u: Signal) -> dict[str, Any]: ...
def is_sig_hbargraph(s: Signal) -> dict[str, Any]: ...
def is_sig_vbargraph(s: Signal) -> dict[str, Any]: ...
def is_sig_attach(s: Signal) -> dict[str, Any]: ...
def is_sig_enable(s: Signal) -> dict[str, Any]: ...
def is_sig_control(s: Signal) -> dict[str, Any]: ...
def is_sig_soundfile(s: Signal) -> dict[str, Any]: ...
def is_sig_soundfile_length(s: Signal) -> dict[str, Any]: ...
def is_sig_soundfile_rate(s: Signal) -> dict[str, Any]: ...
def is_sig_soundfile_buffer(s: Signal) -> dict[str, Any]: ...
