version: '3'

# taskfile: curently only used on windows
# see: https://taskfile.dev/installation

env:
  PYTHON: python.exe
  STATIC: 0

tasks:
  setup:
    cmds:
      - $PYTHON scripts/setup_cyfaust.py --faust

  build:
    cmds:
      - echo '{{OS}} {{ARCH}}'
      - '{{if eq .STATIC "1"}}cmd /C "set STATIC=1 && python setup.py build --build-lib build"{{end}}'
      - '{{if eq .STATIC "0"}}python setup.py build --build-lib build{{end}}'
      - '{{if eq .STATIC "0"}}cp lib/faust.dll ./build/cyfaust{{end}}'
      - cp -rf resources ./build/cyfaust/resources

  demo:
    cmds:
      - echo STATIC=$STATIC

  wheel:
    cmds:
      - env STATIC=$STATIC $PYTHON scripts/wheel_mgr.py --build

  release:
    cmds:
      - python scripts/wheel_mgr.py --release

  test_wheel:
    cmds:
      - $PYTHON scripts/wheel_mgr.py --test

  pytest:
    cmds:
      - pytest -vv .\\tests

  clean:
    silent: true
    cmds:
      - rm -rf build dist venv .venv MANIFEST.in
      - rm -rf .*_cache **/.*_cache
      - rm -rf *.egg-info **/*.egg-info
      - rm -rf **/__pycache__

  reset:
    silent: true
    cmds:
      - rm -rf python bin lib share wheels
