
name: cyfaust-test

on:
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Please select a build variant
        default: dynamic
        required: true
        options: 
          - dynamic
          - static
      py_version:
        type: choice
        description: Please select a python version
        default: '3.11'
        required: true
        options:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
      os:
        type: choice
        description: Please select os
        default: 'macos-latest'
        required: true
        options:
          - macos-latest
          - macos-12
          - macos-11
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}

    steps:

    - name: Display g++ version
      run: clang++ --version

    - name: Display clang++ version
      run: g++ --version
